import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="w-screen min-h-screen flex bg-white dark:bg-[#111210]">
          <Sidebar />
          <div className="w-[calc(100%-256px)] flex flex-col">
            <main className="h-screen overflow-auto">
              <Header />
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
